
name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Run tests
        run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts
          registry-url: https://registry.npmjs.org/
          scope: '@leafty'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts
          registry-url: $registry-url(npm)
          scope: '@leafty'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
